Controllers/ImportedViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniverseObjects.Controllers
{
    public class ImportedViewsController : Controller
    {
        // GET: ImportedViews
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DeviceAVObjects()
        {
            return View();
        }

        public ActionResult EmptyPage()
        {
            return View();
        }

        public ActionResult StandAlone2D()
        {
            return View();
        }

    }
}

Controllers/UniverseObjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniverseObjects.Models;

namespace UniverseObjects.Controllers
{
    public class UniverseObjectsController : Controller
    {
        private Entities db = new Entities();

        // GET: UniverseObjects
        public async Task<ActionResult> Index()
        {
            return View(await db.UniverseObjects.ToListAsync());
        }

        public async Task<ActionResult> _RenderObjectLayout()
        {
            return View();
        }

        public async Task<ActionResult> RenderGalaxy()
        {
            return View();
        }

        public async Task<ActionResult> RenderGLBObject()
        {
            return View();
        }

        public async Task<ActionResult> RenderUniverseObjectControls()
        {
            return View();
        }

        public ActionResult _UniverseObjectLayout()
        {
            return View();
        }

        public ActionResult Home ()
        {
            return View();
        }

        public ActionResult UniverseObjectRendererMenu()
        {
            return View();
        }

        public async Task<ActionResult> RenderObject()
        {
            return View();
        }


        public async Task<ActionResult> RenderStar(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UniverseObject universeObject = await db.UniverseObjects.FindAsync(id);
            if (universeObject == null)
            {
                return HttpNotFound();
            }

            JsonResult universeObjectJson = Json(universeObject);
            universeObjectJson.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            return universeObjectJson;

        }

        // GET: UniverseObjects/Details/5
        public JsonResult UniverseObjectJSON(long? id)
        {
            if (id == null)
            {
                return null;
            }
            UniverseObject universeObject = new UniverseObject();
            UniverseObject dbUniverseObject = db.UniverseObjects.Find(id);

            JsonResult universeObjectJson = new JsonResult();

            if (dbUniverseObject != null)
            {
                universeObjectJson = Json(dbUniverseObject, JsonRequestBehavior.AllowGet);
            } else
            {
                universeObjectJson = Json(universeObject, JsonRequestBehavior.AllowGet);
            }
            return universeObjectJson;
        }

        public async Task<ActionResult> Renderer(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UniverseObject universeObject = await db.UniverseObjects.FindAsync(id);
            if (universeObject == null)
            {
                return HttpNotFound();
            }
            return View(universeObject);
        }

        // GET: UniverseObjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UniverseObjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "UniverseObjectID,UniverseObjectName,UniverseObjectDescription,UniverseObjectPositionVectorX,UniverseObjectPositionVectorY,UniverseObjectPositionVectorZ,UniverseObjectQuaternionVectorX,UniverseObjectQuaternionVectorY,UniverseObjectQuaternionVectorZ,UniverseObjectQuaternionVectorW,UniverseObjectIsSpheroid,UniverseObjectIsPlasma,UniverseObjectHasEventHorizon,UniverseObjectParentID,UniverseObjectOrbitalEccentricity,UniverseObjectAregumentOfPeriapsis,UniverseObjectOrbitalTrueAnomoly,UniverseObjectOrbitalOmegaLongitude,UniverseObjectOrbitalSemiMajorAxis,UniverseObjectOrbitalInclination,UniverseObjectMass,UniverseObjectEquirectangularTextureMapPath,UniverseObjectParentDescription,UniverseObjectEquirectangularVectorDisplacementMapPath,UniverseObjectUseEquirectangularVectorDisplacementMap,UniverseObjectUseEquirectangularTextureMap,UniverseObjectUseEquirectangularVideoTextureMap,UniverseObjectWireframeColor,UniverseObjectHasAtmosphere,UniverseObjectEquirectangularVideoTexturePath,UniverseObjectAtmosphereEquirectangularVectorDisplacementMap,UniverseObjectUseAtmosphereEquirectangularTextureMap,UniverseObjectAtmosphereEquirectangularTextureMapPath,UniverseObjectGLBObjectID,UniverseObjectInitialTemporalArgument,UniverseObjectRendererMaterialID,UniverseObjectGeometryID,UniverseObjectTypeID,UniverseObjectRecordBorn,UniverseObjectUniverseContainerID,UniverseObjectRecordCreatedByUserID,UnierseObjectRecordModified,UniverseObjectRecordModifiedByUserID")] UniverseObject universeObject)
        {
            if (ModelState.IsValid)
            {
                db.UniverseObjects.Add(universeObject);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(universeObject);
        }

        // GET: UniverseObjects/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UniverseObject universeObject = await db.UniverseObjects.FindAsync(id);
            if (universeObject == null)
            {
                return HttpNotFound();
            }
            return View(universeObject);
        }

        // POST: UniverseObjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UniverseObjectID,UniverseObjectName,UniverseObjectDescription,UniverseObjectPositionVectorX,UniverseObjectPositionVectorY,UniverseObjectPositionVectorZ,UniverseObjectQuaternionVectorX,UniverseObjectQuaternionVectorY,UniverseObjectQuaternionVectorZ,UniverseObjectQuaternionVectorW,UniverseObjectIsSpheroid,UniverseObjectIsPlasma,UniverseObjectHasEventHorizon,UniverseObjectParentID,UniverseObjectOrbitalEccentricity,UniverseObjectAregumentOfPeriapsis,UniverseObjectOrbitalTrueAnomoly,UniverseObjectOrbitalOmegaLongitude,UniverseObjectOrbitalSemiMajorAxis,UniverseObjectOrbitalInclination,UniverseObjectMass,UniverseObjectEquirectangularTextureMapPath,UniverseObjectParentDescription,UniverseObjectEquirectangularVectorDisplacementMapPath,UniverseObjectUseEquirectangularVectorDisplacementMap,UniverseObjectUseEquirectangularTextureMap,UniverseObjectUseEquirectangularVideoTextureMap,UniverseObjectWireframeColor,UniverseObjectHasAtmosphere,UniverseObjectEquirectangularVideoTexturePath,UniverseObjectAtmosphereEquirectangularVectorDisplacementMap,UniverseObjectUseAtmosphereEquirectangularTextureMap,UniverseObjectAtmosphereEquirectangularTextureMapPath,UniverseObjectGLBObjectID,UniverseObjectInitialTemporalArgument,UniverseObjectRendererMaterialID,UniverseObjectGeometryID,UniverseObjectTypeID,UniverseObjectRecordBorn,UniverseObjectUniverseContainerID,UniverseObjectRecordCreatedByUserID,UnierseObjectRecordModified,UniverseObjectRecordModifiedByUserID")] UniverseObject universeObject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(universeObject).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(universeObject);
        }

        // GET: UniverseObjects/UniverseObjectRenderer/5
        public async Task<ActionResult> UniverseObjectRenderer(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UniverseObject universeObject = await db.UniverseObjects.FindAsync(id);
            if (universeObject == null)
            {
                return HttpNotFound();
            }
            return View(universeObject);
        }

        // POST: UniverseObjects/UniverseObjectRenderer/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]

Views/ImportedViews/DeviceAVObjects.cshtml

@{
    Layout = null;
}


<style>
    /* Background styles */
    @@font-face {
        font-family: audiowide;
        src: url('/fonts/audiowide.ttf');
    }

    body {
        font-family: audiowide;
        overflow: hidden;
    }

    #devicesContainer {
        position: absolute;
        top: 0px;
        left: 5vw;
        width: 90vw;
    }

    .deviceAVObject {
        transition: .5s;
        font-size: clamp(16px, 2.4vmax, 36px);
        font-family: audiowide;
        width: clamp(200px, 20vw, 300px);
        height: clamp(120px, 18vh, 240px);
        color: #ffffff;
        display: flex;
        flex-wrap: wrap;
        text-align: center;
        justify-items:flex-start;
        opacity: .9;
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.125);
        overflow: hidden;
    }

        .deviceAVObject:hover {
            -webkit-box-reflect: below 0 linear-gradient(transparent, transparent, rgba(0, 0, 0, 0.5));
            z-index: 99999;
            overflow: visible;
            opacity: 1;
            background-color: rgba(255, 255, 255, .9);
            color: #000000;
            text-shadow: 1px 1px #000000;
        }

        .deviceAVObject a {
            transition: .5s;
            font-size: clamp(12px, 2vmax, 28px);
            color: #00ffff;
            text-shadow: 1px 1px #000000;
            text-align: center;
        }

            .deviceAVObject a:hover {
                font-size: clamp(12px, 2vmax, 28px);
                transition: .5s;
                color: #ff6a00;
                text-shadow: 1px 1px #00ffff;
            }

    .deviceAVObjectContainer {
        height: 100%;
        width: 100%;
        padding: 5vh 5vw 5vh 5vw;
        overflow: hidden;
        background-color: transparent;
    }
</style>



<div id="devicesContainer">
    <button 
            class="
                    themedUI 
                    themedUIBackground 
                    buttons"
            
            onclick="getMedia({audio: true, video: true});">
        REFRESH DEVICES
    </button>
    <div id="deviceEnumerationDIV"
         style="
                background-color: rgba(8, 8, 8, .9);
                width: 100%;
                height: 100%;
                display: flex;
                flex-wrap: wrap;
                background-image: radial-gradient(at 47% 33%, rgba(0, 0, 22, .8) 0, transparent 59%), radial-gradient(at 82% 65%, rgb(255, 109, 0));"

         class="deviceAVObjectContainer">
    </div>
</div>

<script>

 
    

    let stream = null;
    let userDevices = null;
    let constraints = { audio: true, video: true };
    async function getMedia({
        audio,
        video
    }) {
        stream =
            await (navigator.mediaDevices.getUserMedia(constraints));
        enumerateUserDevices();
    }
    //function addListeners() {

    //    var elements=
    //        document.querySelectorAll(".deviceAVObject");

    //    elements.forEach(element => {
    //        alert('loop1');
    //        element.addEventListener("mouseover", function (event) {
    //            var elements =
    //                document.querySelectorAll(".deviceAVObject");

    //            elements.forEach(element => {
    //                element.style.transform = 'scale(.7)';
    //                element.style.opacity = '.6';
    //            });
    //        });
    //        element.addEventListener("mouseout", function (event) {
    //            var elements =
    //                document.querySelectorAll(".deviceAVObject");
    //            elements.forEach(element => {
    //                element.style.transform = 'scale(1)';
    //                element.style.opacity = '1';
    //            })
    //        })
    //    })
    //}


    function enumerateUserDevices() {
        var deviceEnumerationDIV =
            document.getElementById("deviceEnumerationDIV");

        navigator.mediaDevices.enumerateDevices()
            .then(function (devices) {
                userDevices = devices;
                var index = 0;
                devices.forEach(function (device) {

                    var deviceContainer =
                        document.createElement("div");
                    deviceContainer.classList
                        .add("deviceAVObject");

                    deviceContainer
                        .setAttribute("id", "deviceAVObject" + index);

                    deviceContainer
                        .setAttribute("name", device.deviceId);

                    var deviceKind =
                        document.createElement('a');

                    deviceKind.classList
                        .add("themedUI");

                    deviceKind.style
                        .cssText = "width: 100%;"

                    deviceKind.innerText =
                        device.kind;

                    deviceContainer
                        .appendChild(deviceKind);

                    var deviceLabel =
                        document.createElement('a');

                    deviceLabel.classList
                        .add("themedUI");

                    deviceLabel
                        .setAttribute("id", "deviceLink" + index);

                    var javascriptLinkString =
                        "javascript: window.videoPlayers[0]" +
                        ".setSinkId('" +
                        device.deviceId +
                        "')";

                    deviceLabel
                        .setAttribute("href", javascriptLinkString);

                    deviceLabel.style
                        .cssText = "width: 100%; height: 100%;"

                    deviceLabel.innerText =
                        device.label;

                    deviceContainer
                        .appendChild(deviceLabel);

                    deviceEnumerationDIV
                        .appendChild(deviceContainer);

                    deviceContainer.addEventListener('mouseenter', function (event) {
                        var others =
                            document.querySelectorAll(".deviceAVObject");
                        others.forEach(element => {
                            element.style.transition = '1.5s';
                            element.style.transform = 'scale(.5)';
                            element.style.opacity = '.1';
                        });
                        deviceContainer.style.transition = '.1s';
                        deviceContainer.style.transform = 'scale(1.4)';
                        deviceContainer.style.opacity = '1';
                    })

                    deviceContainer.addEventListener('mouseleave', function (event) {
                        var others =
                            document.querySelectorAll(".deviceAVObject");
                        others.forEach(element => {
                            element.style.transition = '.8';
                            element.style.transform = 'scale(1)';
                            element.style.opacity = '1';
                        });
                    })
                    index++;
                });
            })
    }

    getMedia(constraints);

</script>


Views/ImportedViews/StandAlone2D.cshtml


@{
    ViewBag.Title = "MYMEDIAPLAY - MEDIAPLAYER";
    Layout = null;
}
<script src="~/Scripts/jquery-3.7.1.min.js"></script>
<!-- AJAX -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>

<link href="~/Content/vailware.stylesheet.master.css" rel="stylesheet" />
<script src="~/Scripts/vailware.master.library.beta.js"></script>

<style>

/*    .visualizer-container {
        position: absolute;
        bottom: 0px;
        width: 100vw;
        height: 30vh;
        display: inline-block;
        text-align: center;
        background-color: transparent;
        visibility: hidden;
    }
*/
/*    .visualizer-container__bar {
        display: inline-block;
        bottom: 0px;
        background-color: #ffffff;
    }
*/
 /*   .frequencyManipulatorContainer {
        display: inline-block;
        bottom: 0px;
        height: 25vh;
        text-align: center;
        z-index: 101;
        background-color: transparent;
    }
*/
/*    .frequencyManipulatorRangeControl {
        position: absolute;
        left: 0px;
        bottom: 0px;
        background-color: transparent;
        appearance: slider-vertical;
        writing-mode: vertical-lr;
        direction: rtl;
        vertical-align: bottom;
        z-index: 299;
    }
*/
/*    .frequencyLevelDIV {
        bottom: 0px;
        left: 0px;
        display: inline-block;
        z-index: 103;
    }
*/
/*    .frequencyManipulator {
        position: absolute;
        bottom: 0px;
        width: 25vh;
        background-color: transparent;
        transform: rotate(-90deg);
        transform-origin: top left;
        z-index: 299;
    }
*/

/*    #rawAudioData {
        position: absolute;
        top: 0px;
        left: 0px;
        width: 100%;
        height: 30vh;
        display: grid;
        grid-template-rows: 1vmax;
        grid-template-columns: repeat(auto-fit, 1vmax);
        grid-row-gap: 2px;
        grid-column-gap: 2px;
        justify-content: center;
        overflow: auto;
        visibility: hidden;
    }
*/
/*    .controlsLabel {
        font-family: audiowide;
        font-size: clamp(10px, 1.1vmax, 72px);
        color: #ffffff;
    }

    .gainRange {
        width: 30vw;
        background-color: rgba(0, 0, 22, .8);
    }
*/
    #generalObjectTabMenu {
        position: absolute;
        top: 2vh;
        left: 0px;
        width: 100%;
        margin: 5px 5px 5px 5px;
        box-shadow: rgba(255, 255, 255, .7) 20px 20px inset;
        display: grid;
        text-align: center;
        background-color: rgba(0, 0, 0, .8);
        display: flex;
        flex-wrap: wrap;
    }

    .tabMenuItem {
/*        width: 100%;
*/        font-size: clamp(12px, .9vmax, 18px);
        color: #dddddd;
    }

        .tabMenuItem a {
            font-size: clamp(12px, .9vmax, 32px);
            color: #dddddd;
        }

            .tabMenuItem a:hover {
                color: #ffffff;
                background-color: rgba(0, 255, 255, .9);
            }

    .tabPage {
        position: absolute;
        top: 10vh;
        left: 5vw;
        width: 90vw;
        height: 90vh;
        visibility: hidden;
        opacity: 0;
        font-size: clamp(12px, 1vh, 18px);
        color: #00ffff;
        text-align: left;
        width: 100%;
        overflow: auto;
    }

    .tabMenuTitle {
        font-size: clamp(12px, 1.1vmax, 36px);
        color: #ffffff;
        text-align: left;
        text-shadow: .1vmin .1vmin #000000;
    }

    .tabPageTitle {
        font-size: clamp(12px, 1.3vmax, 46px);
        color: #ffffff;
        text-align: left;
        text-shadow: .1vmin .1vmin #000000;
    }

    .frequencyIntegerContainer {
        width: 1vmax;
        font-size: clamp(12px, 1vmax, 46px);
        background-color: rgba(88,0,0,.8);
        color: #ff0000;
    }

    .generalObjectLabel {
        font-size: clamp(14px, 1.1vmax, 38px);
        text-shadow: 3px 3px 3px #000000;
        color: #ffffff;
    }

</style>

<style>
    body {
        background-color: #000000;
        overflow: hidden;
    }

    a {
        font-size: clamp(10px, .9vh, 14px);
        color: #ff5e00;
    }
        a:hover {
            color: #00ff00;
        }
</style>

<body style="background: #000000; overflow: hidden;">

    <div id="title"
         style="
        position: absolute;
        top: 0px;
        right: 0px;
        width: 100%;
        display: flex;
        flex-direction: column ;
        text-align: right;
        margin: 5px 5px 5px 5px;
        z-index: 99;">

        <div style="position: absolute; width: 100%; right: 0px; top: 0px;">
            <label style="
                        font-size: clamp(22px, 2vmax, 36px);
                        color: #ff5e00;
                        font-weight: 700;"
                   class="glowingOrange">
                MYMEDIAPLAYER
            </label>
            <br />
            <label style="
                        font-size: clamp(18px, 1.7vmax, 32px);
                        color: #00ffff;
                        font-weight: 500;">
                <i>from mymediaplay.com</i>
            </label>
        </div>

    </div>


    <div id="generalObjectContent"
         style="
            visibility: visible;
            width: 100%;
            position: absolute;
            top: 60px;
            left: 0px;
            background-color: transparent;
            color: #00ffff;">

        <div id="generalObjectTabMenu"
             style="
                    width: 100%;
                    display: flex;
                    flex-wrap: wrap;
                    min-height: 3px;"
             class="themedUI themedUIBackground">


            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'Home' })">
                HOME
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'UniverseObjects' })">
                UNIVERSE OBJECTS
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'UniverseObjectsCreate' })">
                CREATE
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'CelestialSpheres' })">
                PLANETS
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'Stars' })">
                STARS
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'Contact' })">
                CONTACT
            </button>

            <button class="tabMenuItem blackBevel themedUI themedUIBackground buttons"
                    onclick="showtabPage({ tabPageID: 'generalObjectSettings' })">
                SETTINGS
            </button>
        </div>



        <div id="tabPageHome"
             class="tabPage"
             style="visibility: hidden;">
            <div style="position: absolute;
                   width: 100%;
                   left: 0px;
                   top: 0px;">
                <label class="tabPageTitle themedUIHighlight">
                    UNIVERSE OBJECT MODELING HOME PAGE.
                </label>
            </div>
            @*@{Html.RenderAction("YoutubeTools", "Home");}*@

        </div>

        <div id="tabPageUniverseObjectsIndex"
             class="tabPage"
             style="visibility: visible;">
            <div style="
                        position: absolute;
                        width: 100vw;
                        height: 80vh;
                        left: 0px;
                        top: 0px;
                        display: flex;
                        flex-direction: column;">

                <div style="position: absolute;
                   width: 100%;
                   left: 0px;
                   top: 0px;">
                    <label class="tabPageTitle themedUIHighlight">
                        UNIVERSE OBJECTS
                    </label>
                </div>
                <div style="
                            display: flex;
                            flex-wrap: wrap;
                            width: 100%;
                            height: auto;
                            max-height: 70vh;">
                    @{Html.RenderAction("Index", "UniverseObjects");}*@
                </div>

            </div>
        </div>

        <div id="tabPageUniverseObjectsCreate"
             class="tabPage"
             style="visibility: visible;">
            <div style="
                        position: absolute;
                        width: 100vw;
                        height: 80vh;
                        left: 0px;
                        top: 0px;
                        display: flex;
                        flex-direction: column;">

                <div style="position: absolute;
                   width: 100%;
                   left: 0px;
                   top: 0px;">
                    <label class="tabPageTitle themedUIHighlight">
                        CREATE UNIVERSE OBJECT
                    </label>
                </div>
                <div style="
                            display: flex;
                            flex-wrap: wrap;
                            width: 100%;
                            height: auto;
                            max-height: 70vh;">
                    @{Html.RenderAction("Create", "UniverseObjects");}*@
                </div>

            </div>
        </div>

    </div>
</body>

<script>
    function showtabPage({
        tabPageID
    }) {

        var tabPages = document.querySelectorAll('.tabPage');
        tabPages.forEach(tabPage => {
            tabPage.style.transition = '2s';
            tabPage.style.visibility = 'hidden';
            tabPage.style.transform = 'rotateY(180deg)';
            tabPage.style.opacity = '0';

        });

        var tabPage =
            document.getElementById(tabPageID);

        tabPage.style.transition = ".5s";
        tabPage.style.visibility = "visible";
        tabPage.style.transform = "rotateY(0deg)";
        tabPage.style.opacity = "1";

    }
</script>